// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma-next/target-postgres/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:195e873e4c8a5677407c1a8efa2ab8646813be7d94ffdbb20501a3464d90a9f9'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:1f1e7f82ee856ce1bf3c2e3780948382c962c682cd7298764050ec473cb2bf71'>;
export type ProfileHash =
  ProfileHashBase<'sha256:9c8aa3114e84ed3b7ea2bd57526d9c2e1bf7c5292be694e9d3801f566fda7ccb'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Budget: {
      readonly id: Char<36>;
      readonly userId: CodecTypes['pg/text@1']['output'];
      readonly subcategoryId: Char<36>;
      readonly monthlyAmount: CodecTypes['pg/numeric@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly Category: {
      readonly id: Char<36>;
      readonly userId: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly color: CodecTypes['pg/text@1']['output'];
      readonly icon: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly FixedExpense: {
      readonly id: Char<36>;
      readonly userId: CodecTypes['pg/text@1']['output'];
      readonly subcategoryId: Char<36>;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly estimatedAmount: CodecTypes['pg/numeric@1']['output'];
      readonly dueDay: CodecTypes['pg/int4@1']['output'];
      readonly active: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly Subcategory: {
      readonly id: Char<36>;
      readonly userId: CodecTypes['pg/text@1']['output'];
      readonly categoryId: Char<36>;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly type: CodecTypes['pg/text@1']['output'];
      readonly icon: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly Transaction: {
      readonly id: Char<36>;
      readonly userId: CodecTypes['pg/text@1']['output'];
      readonly type: CodecTypes['pg/text@1']['output'];
      readonly subcategoryId: Char<36>;
      readonly fixedExpenseId: Char<36> | null;
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly amount: CodecTypes['pg/numeric@1']['output'];
      readonly isFixed: CodecTypes['pg/bool@1']['output'];
      readonly periodMonth: CodecTypes['pg/text@1']['output'];
      readonly dueDate: CodecTypes['pg/timestamptz@1']['output'] | null;
      readonly paidAmount: CodecTypes['pg/numeric@1']['output'] | null;
      readonly paidDate: CodecTypes['pg/timestamptz@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
    readonly UserSettings: {
      readonly id: Char<36>;
      readonly userId: CodecTypes['pg/text@1']['output'];
      readonly monthStartDay: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Budget: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
      readonly subcategoryId: CodecTypes['sql/char@1']['input'];
      readonly monthlyAmount: CodecTypes['pg/numeric@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly Category: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly color: CodecTypes['pg/text@1']['input'];
      readonly icon: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly FixedExpense: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
      readonly subcategoryId: CodecTypes['sql/char@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly estimatedAmount: CodecTypes['pg/numeric@1']['input'];
      readonly dueDay: CodecTypes['pg/int4@1']['input'];
      readonly active: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly Subcategory: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
      readonly categoryId: CodecTypes['sql/char@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly type: CodecTypes['pg/text@1']['input'];
      readonly icon: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly Transaction: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
      readonly type: CodecTypes['pg/text@1']['input'];
      readonly subcategoryId: CodecTypes['sql/char@1']['input'];
      readonly fixedExpenseId: CodecTypes['sql/char@1']['input'] | null;
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly amount: CodecTypes['pg/numeric@1']['input'];
      readonly isFixed: CodecTypes['pg/bool@1']['input'];
      readonly periodMonth: CodecTypes['pg/text@1']['input'];
      readonly dueDate: CodecTypes['pg/timestamptz@1']['input'] | null;
      readonly paidAmount: CodecTypes['pg/numeric@1']['input'] | null;
      readonly paidDate: CodecTypes['pg/timestamptz@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
    readonly UserSettings: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
      readonly monthStartDay: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly Budget: {
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly id: Char<36>;
      readonly monthlyAmount: CodecTypes['pg/numeric@1']['output'];
      readonly subcategoryId: Char<36>;
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly Category: {
      readonly color: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly icon: CodecTypes['pg/text@1']['output'];
      readonly id: Char<36>;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly FixedExpense: {
      readonly active: CodecTypes['pg/bool@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly dueDay: CodecTypes['pg/int4@1']['output'];
      readonly estimatedAmount: CodecTypes['pg/numeric@1']['output'];
      readonly id: Char<36>;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly subcategoryId: Char<36>;
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly Subcategory: {
      readonly categoryId: Char<36>;
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly icon: CodecTypes['pg/text@1']['output'];
      readonly id: Char<36>;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly type: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly Transaction: {
      readonly amount: CodecTypes['pg/numeric@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly dueDate: CodecTypes['pg/timestamptz@1']['output'] | null;
      readonly fixedExpenseId: Char<36> | null;
      readonly id: Char<36>;
      readonly isFixed: CodecTypes['pg/bool@1']['output'];
      readonly paidAmount: CodecTypes['pg/numeric@1']['output'] | null;
      readonly paidDate: CodecTypes['pg/timestamptz@1']['output'] | null;
      readonly periodMonth: CodecTypes['pg/text@1']['output'];
      readonly subcategoryId: Char<36>;
      readonly type: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
    readonly UserSettings: {
      readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly id: Char<36>;
      readonly monthStartDay: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
      readonly userId: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly Budget: {
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly monthlyAmount: CodecTypes['pg/numeric@1']['input'];
      readonly subcategoryId: CodecTypes['sql/char@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly Category: {
      readonly color: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly icon: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly FixedExpense: {
      readonly active: CodecTypes['pg/bool@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly dueDay: CodecTypes['pg/int4@1']['input'];
      readonly estimatedAmount: CodecTypes['pg/numeric@1']['input'];
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly subcategoryId: CodecTypes['sql/char@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly Subcategory: {
      readonly categoryId: CodecTypes['sql/char@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly icon: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly type: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly Transaction: {
      readonly amount: CodecTypes['pg/numeric@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly dueDate: CodecTypes['pg/timestamptz@1']['input'] | null;
      readonly fixedExpenseId: CodecTypes['sql/char@1']['input'] | null;
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly isFixed: CodecTypes['pg/bool@1']['input'];
      readonly paidAmount: CodecTypes['pg/numeric@1']['input'] | null;
      readonly paidDate: CodecTypes['pg/timestamptz@1']['input'] | null;
      readonly periodMonth: CodecTypes['pg/text@1']['input'];
      readonly subcategoryId: CodecTypes['sql/char@1']['input'];
      readonly type: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
    readonly UserSettings: {
      readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly monthStartDay: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
      readonly userId: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly Budget: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly subcategoryId: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly monthlyAmount: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Category: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly color: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly icon: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly FixedExpense: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly subcategoryId: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly estimatedAmount: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly dueDay: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly active: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', true>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Subcategory: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly categoryId: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly icon: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly Transaction: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly subcategoryId: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly fixedExpenseId: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly amount: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly isFixed: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly periodMonth: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly dueDate: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: true;
                };
                readonly paidAmount: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: true;
                };
                readonly paidDate: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly columns: readonly ['fixedExpenseId'];
                  readonly name: 'Transaction_fixedExpenseId_idx';
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Transaction';
                    readonly columns: readonly ['fixedExpenseId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'FixedExpense';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly UserSettings: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly userId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly monthStartDay: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['userId'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly Category: { readonly namespace: 'public' & NamespaceId; readonly model: 'Category' };
    readonly Subcategory: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Subcategory';
    };
    readonly FixedExpense: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'FixedExpense';
    };
    readonly Transaction: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Transaction';
    };
    readonly UserSettings: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'UserSettings';
    };
    readonly Budget: { readonly namespace: 'public' & NamespaceId; readonly model: 'Budget' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Budget: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly subcategoryId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly monthlyAmount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
            };
            readonly relations: {
              readonly subcategory: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Subcategory';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['subcategoryId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Budget';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'userId' };
                readonly subcategoryId: { readonly column: 'subcategoryId' };
                readonly monthlyAmount: { readonly column: 'monthlyAmount' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Category: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly color: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly icon: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
            };
            readonly relations: {
              readonly subcategories: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Subcategory';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['categoryId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Category';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'userId' };
                readonly name: { readonly column: 'name' };
                readonly color: { readonly column: 'color' };
                readonly icon: { readonly column: 'icon' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly FixedExpense: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly subcategoryId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly estimatedAmount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly dueDay: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly active: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
            };
            readonly relations: {
              readonly subcategory: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Subcategory';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['subcategoryId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly transactions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Transaction';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['fixedExpenseId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'FixedExpense';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'userId' };
                readonly subcategoryId: { readonly column: 'subcategoryId' };
                readonly name: { readonly column: 'name' };
                readonly estimatedAmount: { readonly column: 'estimatedAmount' };
                readonly dueDay: { readonly column: 'dueDay' };
                readonly active: { readonly column: 'active' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Subcategory: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly categoryId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly icon: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
            };
            readonly relations: {
              readonly category: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Category';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['categoryId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly transactions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Transaction';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['subcategoryId'];
                };
              };
              readonly fixedExpenses: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'FixedExpense';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['subcategoryId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Subcategory';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'userId' };
                readonly categoryId: { readonly column: 'categoryId' };
                readonly name: { readonly column: 'name' };
                readonly type: { readonly column: 'type' };
                readonly icon: { readonly column: 'icon' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Transaction: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly subcategoryId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly fixedExpenseId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly amount: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly isFixed: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly periodMonth: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly dueDate: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly paidAmount: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly paidDate: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
            };
            readonly relations: {
              readonly subcategory: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Subcategory';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['subcategoryId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly fixedExpense: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'FixedExpense';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['fixedExpenseId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Transaction';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'userId' };
                readonly type: { readonly column: 'type' };
                readonly subcategoryId: { readonly column: 'subcategoryId' };
                readonly fixedExpenseId: { readonly column: 'fixedExpenseId' };
                readonly description: { readonly column: 'description' };
                readonly amount: { readonly column: 'amount' };
                readonly isFixed: { readonly column: 'isFixed' };
                readonly periodMonth: { readonly column: 'periodMonth' };
                readonly dueDate: { readonly column: 'dueDate' };
                readonly paidAmount: { readonly column: 'paidAmount' };
                readonly paidDate: { readonly column: 'paidDate' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly UserSettings: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly monthStartDay: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'UserSettings';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'userId' };
                readonly monthStartDay: { readonly column: 'monthStartDay' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensionPacks: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'Budget';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv7' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'Budget';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'Category';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv7' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'Category';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'FixedExpense';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv7' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'FixedExpense';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'Subcategory';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv7' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'Subcategory';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'Transaction';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv7' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'Transaction';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'UserSettings';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv7' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'UserSettings';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
